### ISSUE TITLE
"Unknown error occurred" when installing

### ISSUE THREAD

**Issue by kongjudas** [sindrebroch/ha-pollenvarsel#3]
Installed via HACS and trying to install the integration, I get the "Unknown error occurred" message. I'm trying to get the warnings for Rogaland. The integration has worked nicely until recently. I removed it before I checked the logs, so I'm sorry this is all I've got.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/55403016/187730848-7b180a6b-a91f-4093-b741-4bace3e92dfb.png">

**Comment by Eivind007** [comment]
I've also had issues the last couple of days - maybe related to the same error?

![image](https://user-images.githubusercontent.com/94549742/187766917-752cbf06-d6e5-4c3e-abb9-b254136d5601.png)

This error originated from a custom integration.

Logger: custom_components.pollenvarsel
Source: custom_components/pollenvarsel/models.py:110
Integration: Pollenvarsel (documentation, issues)
First occurred: August 30, 2022 at 20:02:09 (2138 occurrences)
Last logged: 21:36:06

Unexpected error fetching pollenvarsel data: float() argument must be a string or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/pollenvarsel/coordinator.py", line 52, in _async_update_data
    return await self.api.fetch()
  File "/config/custom_components/pollenvarsel/api.py", line 59, in fetch
    formatted_response = PollenvarselResponse.from_dict(data)
  File "/config/custom_components/pollenvarsel/models.py", line 162, in from_dict
    forecast=PollenForecast.from_dict(forecast),
  File "/config/custom_components/pollenvarsel/models.py", line 137, in from_dict
    allergens=Allergen.from_dict(forecast_allergens),
  File "/config/custom_components/pollenvarsel/models.py", line 110, in from_dict
    level=float(allergen["level"]),
TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by sindrebroch** [comment]
Yes, thanks for reporting. The API where the information if fetched is shut down out of season, and the integration does not handle it too well. 

I'll look into handling it better, but it won't have any info until march or so i think.

**Comment by sindrebroch** [comment]
The integration should now handle out-of-season response in version [1.4.0](https://github.com/sindrebroch/ha-pollenvarsel/releases/tag/1.4.0). Please reopen if there are any issues.
